Join table for visits
zamcham/database-vet-clinic pull request #4
Opened 2023-06-10 04:06 UTC by zamcham

Added some many-to-many relationships and write more complex queries to use them to answer questions. Results:

<img width="733" alt="1" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/e1151e20-2c67-442a-b65f-4db5e1889b4b">

<img width="733" alt="2" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/0fa5d34d-0017-443e-97d1-6fe377fff0d6">

<img width="733" alt="3" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/04e468fa-48e6-43ad-9d3d-ac4ddb0ea7aa">

<img width="954" alt="4" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/30a2154c-957b-465b-bf08-751853c6de7b">

<img width="990" alt="5" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/62335840-93d0-4d1d-9ccb-50672eea6156">

<img width="990" alt="6" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/08a3151a-ee2a-4fa3-bd57-28b94da2c745">

<img width="990" alt="7" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/9e5a8a3c-0c26-4843-9657-223c5657e86d">

<img width="990" alt="8" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/59d9dbee-1555-4ab4-8adf-030eabb553ac">

<img width="990" alt="9" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/41d889d1-4e2f-44f6-a537-ffdcfc4441f4">

<img width="990" alt="10" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/bd279083-bfef-486e-815b-73b5ed6f15e0">

<img width="990" alt="11" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/b2371510-6325-4b84-ab74-10ea6fbee6e2">

<img width="990" alt="12" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/90094841-2143-4b3a-aec7-f7ec9e8bed02">

<img width="990" alt="13" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/c9200676-0fe8-48ad-b717-ae801f0f3e6f">

<img width="990" alt="14" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/d5f6f389-4433-4596-9d08-d607d468335e">

<img width="990" alt="15" src="https://github.com/zamcham/database-vet-clinic/assets/115372699/ab7d43b8-af3c-42d0-a714-0ef0b3cc3f7a">

2023-06-10 04:22 UTC, afanimartin requested changes
Hi @zamcham, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Everything that creates or change the tables structure is saved in the schema.sql file.
- Everything that populates tables with data is saved in the data.sql file.
- Everything that is a query that helps to analyze data is saved in the queries.sql file.
- Professional readme template used

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Find me on slack
### Martin Afani

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-10 04:22 UTC, afanimartin commented on schema.sql
> +);
- Please add a new table `Visits`. Should have a schema like below
```
   CREATE TABLE visits (
   animal_id int,
   vet_id int,
   visit_date date -- another name is acceptable
   );
```

2023-06-10 04:22 UTC, afanimartin commented on data.sql
> +VALUES ((SELECT id FROM animals WHERE name = 'Blossom'), (SELECT id FROM vets WHERE name = 'William Tatcher'), '2021-01-11');
- Please insert the following data into `Vets` table
```
   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('William Tatcher', 45, '2000-04-23');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Maisy Smith', 26, '2019-01-17');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Stephanie Mendez', 64, '1981-05-04');

   INSERT INTO vets (name, age, date_of_graduation)
   VALUES ('Jack Harkness', 38, '2008-06-08');
`

2023-06-15 16:07 UTC, christianbiring1 approved these changes
Hi @zamcham , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 

## Highlights
- [ ] Great work on implementing the changes as required by the previous reviewer :+1: 
- [ ] Great job on providing the correct queries to answer all the asked questions :1st_place_medal: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-15 16:18 UTC, merged